package com.example.DO;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_id
     *
     * @mbg.generated Tue Dec 04 00:39:56 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_name
     *
     * @mbg.generated Tue Dec 04 00:39:56 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_age
     *
     * @mbg.generated Tue Dec 04 00:39:56 CST 2018
     */
    private Integer userAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_pass
     *
     * @mbg.generated Tue Dec 04 00:39:56 CST 2018
     */
    private String userPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_salt
     *
     * @mbg.generated Tue Dec 04 00:39:56 CST 2018
     */
    private String userSalt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_nick_name
     *
     * @mbg.generated Tue Dec 04 00:39:56 CST 2018
     */
    private String userNickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_last_login_time
     *
     * @mbg.generated Tue Dec 04 00:39:56 CST 2018
     */
    private Date userLastLoginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_id
     *
     * @return the value of t_user.user_id
     *
     * @mbg.generated Tue Dec 04 00:39:56 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_id
     *
     * @param userId the value for t_user.user_id
     *
     * @mbg.generated Tue Dec 04 00:39:56 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_name
     *
     * @return the value of t_user.user_name
     *
     * @mbg.generated Tue Dec 04 00:39:56 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_name
     *
     * @param userName the value for t_user.user_name
     *
     * @mbg.generated Tue Dec 04 00:39:56 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_age
     *
     * @return the value of t_user.user_age
     *
     * @mbg.generated Tue Dec 04 00:39:56 CST 2018
     */
    public Integer getUserAge() {
        return userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_age
     *
     * @param userAge the value for t_user.user_age
     *
     * @mbg.generated Tue Dec 04 00:39:56 CST 2018
     */
    public void setUserAge(Integer userAge) {
        this.userAge = userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_pass
     *
     * @return the value of t_user.user_pass
     *
     * @mbg.generated Tue Dec 04 00:39:56 CST 2018
     */
    public String getUserPass() {
        return userPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_pass
     *
     * @param userPass the value for t_user.user_pass
     *
     * @mbg.generated Tue Dec 04 00:39:56 CST 2018
     */
    public void setUserPass(String userPass) {
        this.userPass = userPass == null ? null : userPass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_salt
     *
     * @return the value of t_user.user_salt
     *
     * @mbg.generated Tue Dec 04 00:39:56 CST 2018
     */
    public String getUserSalt() {
        return userSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_salt
     *
     * @param userSalt the value for t_user.user_salt
     *
     * @mbg.generated Tue Dec 04 00:39:56 CST 2018
     */
    public void setUserSalt(String userSalt) {
        this.userSalt = userSalt == null ? null : userSalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_nick_name
     *
     * @return the value of t_user.user_nick_name
     *
     * @mbg.generated Tue Dec 04 00:39:56 CST 2018
     */
    public String getUserNickName() {
        return userNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_nick_name
     *
     * @param userNickName the value for t_user.user_nick_name
     *
     * @mbg.generated Tue Dec 04 00:39:56 CST 2018
     */
    public void setUserNickName(String userNickName) {
        this.userNickName = userNickName == null ? null : userNickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_last_login_time
     *
     * @return the value of t_user.user_last_login_time
     *
     * @mbg.generated Tue Dec 04 00:39:56 CST 2018
     */
    public Date getUserLastLoginTime() {
        return userLastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_last_login_time
     *
     * @param userLastLoginTime the value for t_user.user_last_login_time
     *
     * @mbg.generated Tue Dec 04 00:39:56 CST 2018
     */
    public void setUserLastLoginTime(Date userLastLoginTime) {
        this.userLastLoginTime = userLastLoginTime;
    }
}